#!/bin/bash

#this script minimize the files created after running
#``npx create-react-app myapp`` for learning purposes

indexjs="import React from 'react'
import ReactDOM from 'react-dom'

class App extends React.Component {
  render() {
    return (
      <div className='App'>
        <h1>Hello, React!</h1>
      </div>
    )
  }
}

ReactDOM.render(<App />, document.getElementById('root'))
"

recycle src > /dev/null
mkdir src
echo "$indexjs" > src/index.js
